{% set name = "tryceratops" %}
{% set version = "2.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tryceratops-{{ version }}.tar.gz
  sha256: 21fa82059fe272f9731db701b720d78eff8dcf84248e97581419a2992ee6a02e

build:
  number: 0
  noarch: python
  entry_points:
    - tryceratops = tryceratops.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.8.1,<4.0.0
  run:
    - click >=7
    - python >=3.8.1,<4.0.0
    - rich >=10.14.0
    - tomli >=2.0.1,<3.0.0
    - typing-extensions >=4.5.0

test:
  imports:
    - tryceratops
  commands:
    - pip check
    - tryceratops --help
  requires:
    - pip

about:
  home: https://github.com/guilatrova/tryceratops
  summary: A linter to manage all your python exceptions and try/except blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
