{% set name = "tryceratops" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tryceratops-{{ version }}.tar.gz
  sha256: a77dd4ed9477736e947142c2439b98a0a8635003c2efd50c03c9419b4ed2c44d

build:
  number: 0
  noarch: python
  entry_points:
    - tryceratops = tryceratops.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - poetry
    - pip
    - python >=3.8
  run:
    - click >=7
    - python >=3.8
    - toml >=0.10.2

test:
  imports:
    - tryceratops
    - tryceratops.analyzers
  commands:
    - pip check
    - tryceratops --help
  requires:
    - pip

about:
  home: https://github.com/guilatrova/tryceratops
  summary: A linter to manage all your python exceptions and try/except blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
