{% set name = "tryceratops" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tryceratops-{{ version }}.tar.gz
  sha256: 30870d05548eee15b3fdaf128396eeff9d47bc97fcc91766e322d204f2d2e79e

build:
  number: 0
  noarch: python
  entry_points:
    - tryceratops = tryceratops.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - poetry
    - pip
    - python >=3.8
  run:
    - click >=7,<9
    - python >=3.8
    - rich >=10.14.0
    - toml >=0.10.2

test:
  imports:
    - tryceratops
    - tryceratops.analyzers
  commands:
    - pip check
    - tryceratops --help
  requires:
    - pip

about:
  home: https://github.com/guilatrova/tryceratops
  summary: A linter to manage all your python exceptions and try/except blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
