{% set name = "tryceratops" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tryceratops-{{ version }}.tar.gz
  sha256: 7ab89c512e1f0c5b04479e895601527d10ba9aa04f0863f143bde95c5532f75e

build:
  number: 0
  noarch: python
  entry_points:
    - tryceratops = tryceratops.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core ==3.2.0
    - poetry-core >=1.0.0
    - pip
    - python >=3.8
  run:
    - click >=7,<9
    - python >=3.8
    - rich >=10.14.0
    - toml >=0.10.2

test:
  imports:
    - tryceratops
    - tryceratops.analyzers
  commands:
    - pip check
    - tryceratops --help
  requires:
    - pip

about:
  home: https://github.com/guilatrova/tryceratops
  summary: A linter to manage all your python exceptions and try/except blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
