{% set name = "tryceratops" %}
{% set version = "2.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tryceratops-{{ version }}.tar.gz
  sha256: e9d77811d8f7d886c4ceaeadccd2675c6f2d794344775463faf1cb969e49d865

build:
  number: 0
  noarch: python
  entry_points:
    - tryceratops = tryceratops.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.8,<4.0
  run:
    - click >=7
    - python >=3.8,<4.0
    - rich >=10.14.0
    - toml >=0.10.2

test:
  imports:
    - tryceratops
  commands:
    - pip check
    - tryceratops --help
  requires:
    - pip

about:
  home: https://github.com/guilatrova/tryceratops
  summary: A linter to manage all your python exceptions and try/except blocks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
